### ISSUE TITLE
[Suggestion] Regarding Array

### ISSUE THREAD

**Issue by dextel2** [murtuzaalisurti/matrices#3]
Redeclaring variables[Array] inside loops is not a good practice

https://github.com/murtuzaalisurti/matrices/blob/32a405a3f4059d5feccaa0106f47c7b8780d83b9/js/app.js#L34
https://github.com/murtuzaalisurti/matrices/blob/32a405a3f4059d5feccaa0106f47c7b8780d83b9/js/app.js#L29

so and so forth

- Keep code clean
- `setTimeout` often regards patchwork
- https://github.com/murtuzaalisurti/matrices/blob/32a405a3f4059d5feccaa0106f47c7b8780d83b9/js/app.js#L857

**Comment by murtuzaalisurti** [comment]
Noted.

**Comment by murtuzaalisurti** [comment]
Fixed.
